networks:
  portfolio:
    external: false

services:
  app:
    build: .
    networks:
      - portfolio
    ports:
      - "4441:4441"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./html/:/app/html/
      - ./css:/app/css/
      - ./assets/:/app/assets/
        ./backend-config.toml:/app/backend-config.toml
    restart: always
